apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: hub-a-traefik-origin
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: hub-a-traefik-origin
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-ingress
    homelab.dev/cluster: hub-a
    homelab.dev/owner: platform
    homelab.dev/tier: platform-secret
spec:
  path: pki_int/issue/hub-a-traefik-origin
  method: POST
  resultType: Data
  parameters:
    common_name: dsqr.dev
    alt_names: >-
      admin.tastingswithtay.com,
      api.fidara.io,
      argocd.hub-a.home.arpa,
      argocd-hooks-hub-a.dsqr.dev,
      fidara.io,
      labs.dsqr.dev,
      studio.dsqr.dev,
      tastingswithtay.com
    ttl: 720h
  provider:
    server: https://vault.service.home.arpa:8200
    caProvider:
      type: ConfigMap
      name: dsqr-home-root-ca
      key: ca.crt
    auth:
      kubernetes:
        mountPath: kubernetes
        role: hub-a-traefik-origin-issuer
        serviceAccountRef:
          name: traefik-origin-issuer
