apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-hub-a
  labels:
    app.kubernetes.io/name: vault-hub-a
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-secrets
    homelab.dev/cluster: hub-a
    homelab.dev/owner: platform
    homelab.dev/tier: platform-addon
spec:
  provider:
    vault:
      server: https://vault.service.home.arpa:8200
      caProvider:
        type: ConfigMap
        name: dsqr-home-root-ca
        key: ca.crt
        namespace: external-secrets
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: hub-a-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
