apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: indigo-gateway-origin
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: indigo-gateway-origin
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-ingress
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-secret
spec:
  path: pki_int/issue/indigo-gateway-origin
  method: POST
  resultType: Data
  parameters:
    common_name: gateway.indigo.home.arpa
    alt_names: argocd.indigo.home.arpa
    ttl: 720h
  provider:
    server: https://vault.service.home.arpa:8200
    caProvider:
      type: ConfigMap
      name: dsqr-home-root-ca
      key: ca.crt
    auth:
      kubernetes:
        mountPath: kubernetes-indigo
        role: indigo-gateway-origin-issuer
        serviceAccountRef:
          name: gateway-origin-issuer
