apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-indigo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: vault-indigo
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-secrets
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-addon
spec:
  provider:
    vault:
      server: https://vault.service.home.arpa:8200
      caProvider:
        type: ConfigMap
        name: dsqr-home-root-ca
        key: ca.crt
        namespace: external-secrets
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-indigo
          role: indigo-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
