apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/gitops-policy/steady-state

resources:
  - argocd-access.yaml
  - argocd-config.yaml
  - cilium.yaml
  - cluster-foundation.yaml
  - external-secrets.yaml
  - external-secrets-config.yaml
  - envoy-gateway.yaml
  - gateway-api.yaml
  - gateway.yaml
  - kubelet-csr-approver.yaml
  - metallb.yaml
  - metallb-config.yaml
  - metrics-server.yaml

labels:
  - pairs:
      platform.dsqr.dev/cluster: indigo
      platform.dsqr.dev/environment: production

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cilium
    patch: |-
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1version
        value: 1.20.1
      - op: replace
        path: /spec/sources/0/targetRevision
        value: 1.20.1
