apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fidara-repo
  namespace: argocd
  labels:
    app.kubernetes.io/name: fidara-repo
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-secrets
    homelab.dev/owner: platform
    homelab.dev/tier: platform-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-hub-a
    kind: ClusterSecretStore
  target:
    name: fidara-repo
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: fidara-repo
          app.kubernetes.io/managed-by: external-secrets
          argocd.argoproj.io/secret-type: repository
          homelab.dev/owner: platform
          homelab.dev/tier: platform-secret
  data:
    - secretKey: type
      remoteRef:
        key: homelab/platform/argocd/repos/fidara
        property: type
    - secretKey: url
      remoteRef:
        key: homelab/platform/argocd/repos/fidara
        property: url
    - secretKey: username
      remoteRef:
        key: homelab/platform/argocd/repos/fidara
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/platform/argocd/repos/fidara
        property: password
