apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: argocd-github-webhook
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
    homelab.dev/cluster: hub-a
    homelab.dev/owner: platform
    homelab.dev/tier: platform-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-hub-a
    kind: ClusterSecretStore
  target:
    name: argocd-github-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-github-webhook
          app.kubernetes.io/managed-by: external-secrets
          app.kubernetes.io/part-of: argocd
          homelab.dev/cluster: hub-a
          homelab.dev/owner: platform
          homelab.dev/tier: platform-secret
  data:
    - secretKey: secret
      remoteRef:
        key: homelab/platform/argocd/webhooks/github
        property: secret
