apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - fidara-repo.externalsecret.yaml
  - github-webhook.externalsecret.yaml
  - github-webhook.traefik.yaml

labels:
  - pairs:
      homelab.dev/cluster: hub-a
      homelab.dev/environment: homelab
