apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dmz-ingress.ciliumnetworkpolicy.yaml

components:
  - ../../network-policy

labels:
  - pairs:
      platform.dsqr.dev/cluster: indigo
      platform.dsqr.dev/environment: production

patches:
  - target:
      group: cilium.io
      kind: CiliumNetworkPolicy
      name: envoy-gateway-controller-access
    patch: |-
      - op: replace
        path: /spec/ingress/3/fromEndpoints/0/matchLabels/app.kubernetes.io~1instance
        value: indigo-metrics
      - op: replace
        path: /spec/ingress/3/fromEndpoints/0/matchLabels/app.kubernetes.io~1name
        value: alloy
  - target:
      group: cilium.io
      kind: CiliumNetworkPolicy
      name: envoy-shared-proxy-access
    patch: |-
      - op: replace
        path: /spec/ingress/1/fromEndpoints/0/matchLabels/app.kubernetes.io~1instance
        value: indigo-metrics
      - op: replace
        path: /spec/ingress/1/fromEndpoints/0/matchLabels/app.kubernetes.io~1name
        value: alloy
  - target:
      group: gateway.envoyproxy.io
      version: v1alpha1
      kind: EnvoyProxy
      name: shared
    patch: |-
      - op: add
        path: /spec/provider/kubernetes/envoyDeployment/pod/nodeSelector
        value:
          platform.dsqr.dev/node-pool: platform
      - op: add
        path: /spec/provider/kubernetes/envoyDeployment/pod/tolerations
        value:
          - key: platform.dsqr.dev/dedicated
            operator: Equal
            value: platform
            effect: NoSchedule
      - op: add
        path: /spec/provider/kubernetes/envoyDeployment/pod/topologySpreadConstraints/0/minDomains
        value: 2
      - op: add
        path: /spec/provider/kubernetes/envoyDeployment/pod/topologySpreadConstraints/0/nodeTaintsPolicy
        value: Honor
      - op: add
        path: /spec/provider/kubernetes/envoyService/annotations/metallb.io~1loadBalancerIPs
        value: 10.10.80.200
