import assert from "node:assert/strict"
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import test from "node:test"

import { NodeContext } from "@effect/platform-node"
import { Effect } from "effect"

import { generateGitOps, parseGitOpsGenerateArguments } from "../packages/gitops/src/generate.ts"

const runWithNode = <A, E, R>(effect: Effect.Effect<A, E, R>) =>
  Effect.runPromise(effect.pipe(Effect.provide(NodeContext.layer)))

const generatedMarker = "# Generated by `nix run .#gitops-generate`."

const createFixture = async (resources: readonly string[] = ["demo.yaml"]) => {
  const root = await mkdtemp(join(tmpdir(), "gitops-generate-"))
  const applications = join(root, "gitops", "clusters", "test-a", "applications")
  const bootstrap = join(root, "gitops", "clusters", "test-a", "bootstrap")
  const templates = join(root, "gitops", "templates", "applications")
  await Promise.all([
    mkdir(applications, { recursive: true }),
    mkdir(bootstrap, { recursive: true }),
    mkdir(templates, { recursive: true }),
  ])

  await writeFile(
    join(applications, "kustomization.yaml"),
    `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
${resources.map((resource) => `  - ${resource}`).join("\n")}
`,
  )
  await writeFile(
    join(bootstrap, "kustomization.yaml"),
    `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-app-of-apps.yaml
`,
  )
  await writeFile(
    join(bootstrap, "argocd-app-of-apps.yaml"),
    `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-a
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/example/infrastructure.git
    targetRevision: refs/heads/master
    path: gitops/clusters/test-a/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
`,
  )
  await writeFile(
    join(templates, "demo.yaml.tmpl"),
    `${generatedMarker}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: \${APPLICATION_NAME}
  namespace: \${ARGOCD_NAMESPACE}
spec:
  project: demo
  source:
    repoURL: \${VALUES_REPO_URL}
    targetRevision: \${VALUES_TARGET_REVISION}
    path: gitops/components/demo/overlays/\${CLUSTER_NAME}
  destination:
    server: \${DESTINATION_SERVER}
    namespace: demo
`,
  )
  await writeFile(join(applications, "demo.yaml"), `${generatedMarker}\nthis: is stale\n`)
  await writeFile(
    join(applications, "handwritten.yaml"),
    "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: preserve-me\n",
  )

  return { applications, root }
}

test("parses the legacy generator CLI contract", async () => {
  assert.deepEqual(
    await Effect.runPromise(
      parseGitOpsGenerateArguments(["--check", "--repo-root", "/repo"], "/cwd"),
    ),
    { check: true, repoRoot: "/repo" },
  )
  assert.equal(await Effect.runPromise(parseGitOpsGenerateArguments(["--help"], "/cwd")), "help")

  const error = await Effect.runPromise(
    parseGitOpsGenerateArguments(["--repo-root"], "/cwd").pipe(Effect.flip),
  )
  assert.equal(error._tag, "GitOpsUsageError")
  assert.equal(error.message, "--repo-root requires a path")
})

test("renders validated Applications and preserves handwritten YAML", async () => {
  const fixture = await createFixture()
  await runWithNode(generateGitOps({ check: false, repoRoot: fixture.root }))

  const generated = await readFile(join(fixture.applications, "demo.yaml"), "utf8")
  assert.match(generated, /name: demo/)
  assert.match(generated, /namespace: argocd/)
  assert.match(generated, /repoURL: https:\/\/github\.com\/example\/infrastructure\.git/)
  assert.doesNotMatch(generated, /\$\{[A-Z_][A-Z0-9_]*\}/)
  assert.match(
    await readFile(join(fixture.applications, "handwritten.yaml"), "utf8"),
    /preserve-me/,
  )
})

test("failed staging leaves committed generated output untouched", async () => {
  const fixture = await createFixture(["demo.yaml", "missing-template.yaml"])
  const generatedPath = join(fixture.applications, "demo.yaml")
  const before = await readFile(generatedPath, "utf8")

  const error = await runWithNode(
    generateGitOps({ check: false, repoRoot: fixture.root }).pipe(Effect.flip),
  )

  assert.equal(error._tag, "GitOpsValidationError")
  assert.match(error.message, /missing the missing-template template/)
  assert.equal(await readFile(generatedPath, "utf8"), before)
})

test("check mode detects drift without modifying committed output", async () => {
  const fixture = await createFixture()
  const generatedPath = join(fixture.applications, "demo.yaml")
  const before = await readFile(generatedPath, "utf8")

  const error = await runWithNode(
    generateGitOps({ check: true, repoRoot: fixture.root }).pipe(Effect.flip),
  )

  assert.equal(error._tag, "GitOpsValidationError")
  assert.match(error.message, /Generated GitOps output differs/)
  assert.match(error.message, /test-a\/applications\/demo\.yaml/)
  assert.equal(await readFile(generatedPath, "utf8"), before)
})
