import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const read = (path: string) => readFile(new URL(`../${path}`, import.meta.url), "utf8")

test("Indigo platform add-ons are generated from shared Application templates", async () => {
  const kustomization = await read("gitops/clusters/indigo/applications/kustomization.yaml")

  for (const application of [
    "gateway-api",
    "kubelet-csr-approver",
    "metallb",
    "metallb-config",
    "metrics-server",
  ]) {
    assert.match(kustomization, new RegExp(`  - ${application}\\.yaml`))

    const generated = await read(`gitops/clusters/indigo/applications/${application}.yaml`)
    assert.match(generated, /^# Generated by `nix run \.#gitops-generate`\./)
  }
})

test("Indigo pins the Gateway API Standard Channel and its exact cluster permissions", async () => {
  const [application, project] = await Promise.all([
    read("gitops/clusters/indigo/applications/gateway-api.yaml"),
    read("gitops/components/argocd/base/platform-gateway-api.appproject.yaml"),
  ])

  assert.match(application, /repoURL: https:\/\/github\.com\/kubernetes-sigs\/gateway-api\.git/)
  assert.match(application, /targetRevision: 8bb74df00e56ec8f944d48c25e6c1c9c2f6848e3/)
  assert.match(application, /path: config\/crd\/standard/)
  assert.match(application, /- ServerSideApply=true/)
  assert.match(application, /enabled: false/)

  for (const resource of [
    "backendtlspolicies",
    "gatewayclasses",
    "gateways",
    "grpcroutes",
    "httproutes",
    "listenersets",
    "referencegrants",
    "tcproutes",
    "tlsroutes",
    "udproutes",
  ]) {
    assert.match(project, new RegExp(`name: ${resource}\\.gateway\\.networking\\.k8s\\.io`))
  }

  assert.match(project, /kind: ValidatingAdmissionPolicy\n\s+name: safe-upgrades/)
  assert.match(project, /kind: ValidatingAdmissionPolicyBinding\n\s+name: safe-upgrades/)
  assert.doesNotMatch(project, /kind: "\*"|name: "\*"/)
})

test("Indigo foundation declares only current platform namespaces", async () => {
  const namespaces = await read(
    "gitops/components/cluster-foundation/overlays/indigo/namespaces.yaml",
  )
  const names = [...namespaces.matchAll(/^  name: (.+)$/gm)].map((match) => match[1])

  assert.deepEqual(names, ["external-secrets", "metallb-system"])
  assert.match(
    namespaces,
    /name: metallb-system[\s\S]+pod-security\.kubernetes\.io\/enforce: privileged/,
  )
})

test("Indigo MetalLB is isolated to its reserved pool and worker nodes", async () => {
  const [pool, advertisement, values] = await Promise.all([
    read("gitops/components/metallb/overlays/indigo/ipaddresspool.yaml"),
    read("gitops/components/metallb/overlays/indigo/l2advertisement.yaml"),
    read("gitops/components/metallb/overlays/indigo/values-overrides.yaml"),
  ])

  assert.match(pool, /10\.10\.80\.200-10\.10\.80\.249/)
  assert.match(
    advertisement,
    /key: node-role\.kubernetes\.io\/control-plane\n\s+operator: DoesNotExist/,
  )
  assert.match(values, /loadBalancerClass: metallb\.io\/metallb/)
  assert.match(values, /tolerateMaster: false/)
  assert.match(values, /defaultDeny: true/)
})

test("Indigo explicitly enables Cilium's Gateway API and standalone Envoy data plane", async () => {
  const [commonValues, values, project] = await Promise.all([
    read("gitops/components/cilium/base/values-common.yaml"),
    read("gitops/components/cilium/overlays/indigo/values-overrides.yaml"),
    read("gitops/components/argocd/base/platform-cilium.appproject.yaml"),
  ])

  assert.match(commonValues, /^operator:\n(?:.*\n)*?  rollOutPods: true$/m)
  assert.match(values, /^l7Proxy: true$/m)
  assert.match(values, /^envoy:\n  enabled: true$/m)
  assert.match(values, /^gatewayAPI:\n  enabled: true$/m)
  assert.match(
    project,
    /kind: ValidatingAdmissionPolicy\n\s+name: gateway\.cilium\.io/,
  )
  assert.match(
    project,
    /kind: ValidatingAdmissionPolicyBinding\n\s+name: gateway\.cilium\.io/,
  )
  assert.match(project, /kind: GatewayClass\n\s+name: cilium/)
})

test("Indigo Metrics Server keeps kubelet TLS verification enabled", async () => {
  const values = await read(
    "gitops/components/metrics-server/overlays/indigo/values-overrides.yaml",
  )

  assert.match(
    values,
    /--kubelet-certificate-authority=\/var\/run\/secrets\/kubernetes\.io\/serviceaccount\/ca\.crt/,
  )
  assert.doesNotMatch(values, /--kubelet-insecure-tls/)
})

test("Indigo kubelet serving CSR approval is restricted to its six nodes", async () => {
  const values = await read(
    "gitops/components/kubelet-csr-approver/overlays/indigo/values-overrides.yaml",
  )

  assert.match(values, /\^srv-lx-k8s-indigo-\(control\|worker\)-0\[1-3\]\$/)
  for (let address = 100; address <= 105; address += 1) {
    assert.match(values, new RegExp(`10\\.10\\.80\\.${address}/32`))
  }
  assert.match(values, /bypassDnsResolution: true/)
  assert.match(values, /bypassHostnameCheck: false/)
  assert.match(values, /ignoreNonSystemNode: false/)
  assert.match(values, /skipDenyStep: false/)
})
