import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const read = (path: string) => readFile(new URL(`../${path}`, import.meta.url), "utf8")

test("Indigo platform add-ons are generated from shared Application templates", async () => {
  const kustomization = await read("gitops/clusters/indigo/applications/kustomization.yaml")

  for (const application of [
    "argocd-access",
    "gateway",
    "gateway-api",
    "kubelet-csr-approver",
    "metallb",
    "metallb-config",
    "metrics-server",
  ]) {
    assert.match(kustomization, new RegExp(`  - ${application}\\.yaml`))

    const generated = await read(`gitops/clusters/indigo/applications/${application}.yaml`)
    assert.match(generated, /^# Generated by `nix run \.#gitops-generate`\./)
  }
})

test("Indigo pins the Gateway API Standard Channel and its exact cluster permissions", async () => {
  const [application, project] = await Promise.all([
    read("gitops/clusters/indigo/applications/gateway-api.yaml"),
    read("gitops/components/argocd/base/platform-gateway-api.appproject.yaml"),
  ])

  assert.match(application, /repoURL: https:\/\/github\.com\/kubernetes-sigs\/gateway-api\.git/)
  assert.match(application, /targetRevision: 8bb74df00e56ec8f944d48c25e6c1c9c2f6848e3/)
  assert.match(application, /path: config\/crd\/standard/)
  assert.match(application, /- ServerSideApply=true/)
  assert.match(application, /enabled: false/)

  for (const resource of [
    "backendtlspolicies",
    "gatewayclasses",
    "gateways",
    "grpcroutes",
    "httproutes",
    "listenersets",
    "referencegrants",
    "tcproutes",
    "tlsroutes",
    "udproutes",
  ]) {
    assert.match(project, new RegExp(`name: ${resource}\\.gateway\\.networking\\.k8s\\.io`))
  }

  assert.match(project, /kind: ValidatingAdmissionPolicy\n\s+name: safe-upgrades/)
  assert.match(project, /kind: ValidatingAdmissionPolicyBinding\n\s+name: safe-upgrades/)
  assert.doesNotMatch(project, /kind: "\*"|name: "\*"/)
})

test("Indigo foundation declares only current platform namespaces", async () => {
  const namespaces = await read(
    "gitops/components/cluster-foundation/overlays/indigo/namespaces.yaml",
  )
  const names = [...namespaces.matchAll(/^  name: (.+)$/gm)].map((match) => match[1])

  assert.deepEqual(names, ["argocd", "external-secrets", "gateway-system", "metallb-system"])
  assert.match(
    namespaces,
    /name: argocd[\s\S]+platform\.dsqr\.dev\/gateway-access: shared/,
  )
  assert.match(
    namespaces,
    /name: gateway-system[\s\S]+pod-security\.kubernetes\.io\/enforce: baseline/,
  )
  assert.match(
    namespaces,
    /name: metallb-system[\s\S]+pod-security\.kubernetes\.io\/enforce: privileged/,
  )
})

test("Indigo MetalLB reserves the Gateway VIP and advertises only from workers", async () => {
  const [gatewayPool, pool, advertisement, values] = await Promise.all([
    read("gitops/components/metallb/overlays/indigo/gateway-ipaddresspool.yaml"),
    read("gitops/components/metallb/overlays/indigo/ipaddresspool.yaml"),
    read("gitops/components/metallb/overlays/indigo/l2advertisement.yaml"),
    read("gitops/components/metallb/overlays/indigo/values-overrides.yaml"),
  ])

  assert.match(gatewayPool, /10\.10\.80\.200\/32/)
  assert.match(gatewayPool, /autoAssign: false/)
  assert.match(gatewayPool, /argocd\.argoproj\.io\/sync-wave: "1"/)
  assert.match(pool, /10\.10\.80\.201-10\.10\.80\.249/)
  assert.match(pool, /argocd\.argoproj\.io\/sync-wave: "0"/)
  assert.match(advertisement, /ipAddressPools:\n\s+- gateway\n\s+- ingress/)
  assert.match(advertisement, /argocd\.argoproj\.io\/sync-wave: "2"/)
  assert.match(
    advertisement,
    /key: node-role\.kubernetes\.io\/control-plane\n\s+operator: DoesNotExist/,
  )
  assert.match(values, /loadBalancerClass: metallb\.io\/metallb/)
  assert.match(values, /tolerateMaster: false/)
  assert.match(values, /defaultDeny: true/)
})

test("Indigo shared Gateway is generated, HTTPS-only, and restricted by namespace label", async () => {
  const [
    application,
    gateway,
    gatewayOverlay,
    gatewayClass,
    gatewayClassConfig,
    project,
    secretsProjectOverlay,
    issuerServiceAccount,
    issuerAuthDelegator,
    vaultGenerator,
    externalSecret,
  ] =
    await Promise.all([
      read("gitops/clusters/indigo/applications/gateway.yaml"),
      read("gitops/components/gateway/base/shared.gateway.yaml"),
      read("gitops/components/gateway/overlays/indigo/kustomization.yaml"),
      read("gitops/components/gateway/base/cilium-metallb.gatewayclass.yaml"),
      read("gitops/components/gateway/base/cilium-metallb.gatewayclassconfig.yaml"),
      read("gitops/components/argocd/overlays/indigo/platform-gateway.appproject.yaml"),
      read("gitops/components/argocd/overlays/indigo/kustomization.yaml"),
      read(
        "gitops/components/external-secrets-config/overlays/indigo/gateway-origin-issuer.serviceaccount.yaml",
      ),
      read(
        "gitops/components/external-secrets-config/overlays/indigo/gateway-origin-issuer.clusterrolebinding.yaml",
      ),
      read(
        "gitops/components/external-secrets-config/overlays/indigo/indigo-gateway-origin.vaultdynamicsecret.yaml",
      ),
      read(
        "gitops/components/external-secrets-config/overlays/indigo/indigo-gateway-origin.externalsecret.yaml",
      ),
    ])

  assert.match(application, /project: platform-gateway/)
  assert.match(application, /path: gitops\/components\/gateway\/overlays\/indigo/)
  assert.match(application, /enabled: false/)
  assert.match(project, /namespace: gateway-system/)
  assert.match(project, /kind: GatewayClass\n\s+name: cilium-metallb/)
  assert.match(project, /kind: CiliumGatewayClassConfig/)
  assert.match(project, /kind: Gateway/)
  assert.match(gatewayClass, /name: cilium-metallb/)
  assert.match(gatewayClass, /controllerName: io\.cilium\/gateway-controller/)
  assert.match(gatewayClass, /kind: CiliumGatewayClassConfig/)
  assert.match(gatewayClass, /namespace: gateway-system/)
  assert.match(gatewayClass, /argocd\.argoproj\.io\/sync-wave: "1"/)
  assert.match(gatewayClassConfig, /kind: CiliumGatewayClassConfig/)
  assert.match(gatewayClassConfig, /namespace: gateway-system/)
  assert.match(gatewayClassConfig, /loadBalancerClass: metallb\.io\/metallb/)
  assert.match(gatewayClassConfig, /argocd\.argoproj\.io\/sync-wave: "0"/)
  assert.match(gateway, /gatewayClassName: cilium-metallb/)
  assert.match(gateway, /protocol: HTTPS/)
  assert.doesNotMatch(gateway, /protocol: HTTP$/m)
  assert.match(gateway, /metallb\.io\/address-pool: gateway/)
  assert.match(gatewayOverlay, /metallb\.io~1loadBalancerIPs\n\s+value: 10\.10\.80\.200/)
  assert.match(gateway, /platform\.dsqr\.dev\/gateway-access: shared/)
  assert.match(issuerServiceAccount, /automountServiceAccountToken: false/)
  assert.match(issuerServiceAccount, /argocd\.argoproj\.io\/sync-wave: "0"/)
  assert.match(issuerAuthDelegator, /name: gateway-origin-issuer-auth-delegator/)
  assert.match(issuerAuthDelegator, /name: gateway-origin-issuer\n\s+namespace: gateway-system/)
  assert.match(issuerAuthDelegator, /name: system:auth-delegator/)
  assert.match(issuerAuthDelegator, /argocd\.argoproj\.io\/sync-wave: "1"/)
  assert.match(secretsProjectOverlay, /name: gateway-origin-issuer-auth-delegator/)
  assert.match(vaultGenerator, /common_name: gateway\.indigo\.home\.arpa/)
  assert.match(vaultGenerator, /alt_names: argocd\.indigo\.home\.arpa/)
  assert.match(vaultGenerator, /mountPath: kubernetes-indigo/)
  assert.match(vaultGenerator, /role: indigo-gateway-origin-issuer/)
  assert.match(vaultGenerator, /argocd\.argoproj\.io\/sync-wave: "2"/)
  assert.match(externalSecret, /name: gateway-origin-tls/)
  assert.match(externalSecret, /type: kubernetes\.io\/tls/)
  assert.match(externalSecret, /argocd\.argoproj\.io\/sync-wave: "3"/)
})

test("Indigo Argo access separates the private UI from the authenticated public webhook", async () => {
  const [
    application,
    project,
    overlay,
    uiRoute,
    webhookRoute,
    webhookSecret,
    policy,
    values,
    bootstrapProject,
  ] = await Promise.all([
    read("gitops/clusters/indigo/applications/argocd-access.yaml"),
    read("gitops/components/argocd/overlays/indigo/platform-argocd-access.appproject.yaml"),
    read("gitops/components/argocd/access/overlays/indigo/kustomization.yaml"),
    read("gitops/components/argocd/access/overlays/indigo/ui.httproute.yaml"),
    read("gitops/components/argocd/access/overlays/indigo/github-webhook.httproute.yaml"),
    read("gitops/components/argocd/access/overlays/indigo/github-webhook.externalsecret.yaml"),
    read("gitops/components/argocd/access/base/gateway-ingress.ciliumnetworkpolicy.yaml"),
    read("gitops/components/argocd/overlays/indigo/values-overrides.yaml"),
    read("gitops/clusters/indigo/bootstrap/bootstrap.appproject.yaml"),
  ])

  assert.match(application, /project: platform-argocd-access/)
  assert.match(application, /path: gitops\/components\/argocd\/access\/overlays\/indigo/)
  assert.match(application, /argocd\.argoproj\.io\/sync-wave: "5"/)
  assert.match(application, /enabled: false/)
  assert.match(project, /namespace: argocd/)
  assert.match(project, /kind: CiliumNetworkPolicy/)
  assert.match(project, /kind: ExternalSecret/)
  assert.match(project, /kind: HTTPRoute/)
  assert.doesNotMatch(project, /kind: "\*"|name: "\*"/)

  for (const resource of [
    "github-webhook.externalsecret.yaml",
    "github-webhook.httproute.yaml",
    "ui.httproute.yaml",
  ]) {
    assert.match(overlay, new RegExp(`  - ${resource.replaceAll(".", "\\.")}`))
  }

  assert.match(uiRoute, /hostnames:\n\s+- argocd\.indigo\.home\.arpa/)
  assert.match(uiRoute, /name: shared\n\s+namespace: gateway-system\n\s+sectionName: https/)
  assert.match(uiRoute, /name: argocd-server\n\s+port: 80/)
  assert.match(webhookRoute, /hostnames:\n\s+- argocd-hooks-indigo\.dsqr\.dev/)
  assert.match(webhookRoute, /method: POST/)
  assert.match(webhookRoute, /type: Exact\n\s+value: \/api\/webhook/)
  assert.doesNotMatch(webhookRoute, /PathPrefix/)
  assert.match(
    webhookSecret,
    /key: dsqr-labs\/clusters\/indigo\/platform\/argocd\/webhooks\/github/,
  )
  assert.match(webhookSecret, /deletionPolicy: Retain/)
  assert.match(policy, /fromEntities:\n\s+- ingress/)
  assert.match(policy, /port: "8080"/)
  assert.doesNotMatch(policy, /fromEntities:\n\s+- world/)
  assert.match(values, /githubSecret: "\$argocd-github-webhook:secret"/)
  assert.match(bootstrapProject, /kind: Namespace\n\s+name: argocd/)
})

test("Indigo explicitly enables Cilium's Gateway API and standalone Envoy data plane", async () => {
  const [commonValues, values, project] = await Promise.all([
    read("gitops/components/cilium/base/values-common.yaml"),
    read("gitops/components/cilium/overlays/indigo/values-overrides.yaml"),
    read("gitops/components/argocd/base/platform-cilium.appproject.yaml"),
  ])

  assert.match(commonValues, /^operator:\n(?:.*\n)*?  rollOutPods: true$/m)
  assert.match(values, /^l7Proxy: true$/m)
  assert.match(values, /^envoy:\n  enabled: true$/m)
  assert.match(values, /^gatewayAPI:\n  enabled: true$/m)
  assert.match(
    project,
    /kind: ValidatingAdmissionPolicy\n\s+name: gateway\.cilium\.io/,
  )
  assert.match(
    project,
    /kind: ValidatingAdmissionPolicyBinding\n\s+name: gateway\.cilium\.io/,
  )
  assert.match(project, /kind: GatewayClass\n\s+name: cilium/)
})

test("Indigo Metrics Server keeps kubelet TLS verification enabled", async () => {
  const values = await read(
    "gitops/components/metrics-server/overlays/indigo/values-overrides.yaml",
  )

  assert.match(
    values,
    /--kubelet-certificate-authority=\/var\/run\/secrets\/kubernetes\.io\/serviceaccount\/ca\.crt/,
  )
  assert.doesNotMatch(values, /--kubelet-insecure-tls/)
})

test("Indigo kubelet serving CSR approval is restricted to its six nodes", async () => {
  const values = await read(
    "gitops/components/kubelet-csr-approver/overlays/indigo/values-overrides.yaml",
  )

  assert.match(values, /\^srv-lx-k8s-indigo-\(control\|worker\)-0\[1-3\]\$/)
  for (let address = 100; address <= 105; address += 1) {
    assert.match(values, new RegExp(`10\\.10\\.80\\.${address}/32`))
  }
  assert.match(values, /bypassDnsResolution: true/)
  assert.match(values, /bypassHostnameCheck: false/)
  assert.match(values, /ignoreNonSystemNode: false/)
  assert.match(values, /skipDenyStep: false/)
})
