apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-metallb
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: cilium-metallb
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: cluster-ingress
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-addon
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: metallb.io/metallb
