# hub-a Helm value overrides for Traefik.
service:
  annotations:
    metallb.io/address-pool: ingress
    metallb.io/loadBalancerIPs: 10.10.30.200
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - 10.10.60.100/32
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 10.10.60.100/32

tlsStore:
  default:
    defaultCertificate:
      secretName: hub-a-traefik-origin-tls
