apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: argocd-server-tls
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-secret
spec:
  path: pki_int/issue/indigo-argocd-server
  method: POST
  resultType: Data
  parameters:
    common_name: argocd-server.argocd.svc.cluster.local
    ttl: 720h
  provider:
    server: https://vault.service.home.arpa:8200
    caProvider:
      type: ConfigMap
      name: dsqr-home-root-ca
      key: ca.crt
    auth:
      kubernetes:
        mountPath: kubernetes-indigo
        role: indigo-argocd-server-issuer
        serviceAccountRef:
          name: argocd-server-issuer
