apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: argocd-github-webhook
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: argocd
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: vault-indigo
    kind: ClusterSecretStore
  target:
    name: argocd-github-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-github-webhook
          app.kubernetes.io/managed-by: external-secrets
          app.kubernetes.io/part-of: argocd
          platform.dsqr.dev/cluster: indigo
          platform.dsqr.dev/owner: platform
          platform.dsqr.dev/tier: platform-secret
  data:
    - secretKey: secret
      remoteRef:
        key: dsqr-labs/clusters/indigo/platform/argocd/webhooks/github
        property: secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
