import { tags, type VmDefaults, type VmInventory } from "@dsqr/model"

const defaults = {
  cpuCores: 2,
  memoryMiB: 4096,
  rootDiskSizeGiB: 32,
  tags: [],
} satisfies VmDefaults

const vms = {
  gateway: {
    name: "gateway",
    vmId: 1000,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 60,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    tags: tags("network"),
  },
  observability: {
    name: "beacon",
    resourceName: "observability",
    vmId: 1050,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 128,
    tags: tags("observability"),
  },
  khaos: {
    name: "khaos",
    vmId: 1100,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 8,
    memoryMiB: 8192,
    rootDiskSizeGiB: 200,
    discard: true,
    tags: tags("compute"),
  },
  knox: {
    name: "knox",
    vmId: 1120,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:20",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 16384,
    rootDiskSizeGiB: 200,
    tags: tags("compute"),
  },
  vault: {
    name: "vault",
    vmId: 1140,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:40",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 64,
    tags: tags("vault"),
  },
  backup: {
    name: "backup",
    vmId: 1160,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:60",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 128,
    dataDisks: [
      {
        interface: "scsi1",
        datastoreId: "local-lvm",
        sizeGiB: 512,
        backup: false,
        discard: true,
        replicate: false,
        serial: "backup-data",
      },
    ],
    tags: tags("backup"),
  },
  pantheon: {
    name: "pantheon",
    vmId: 1180,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:80",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 64,
    tags: tags("agents"),
  },
  k8sMainCp1: {
    name: "k8s-main-cp-01",
    vmId: 1200,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 16384,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
  k8sMainW1: {
    name: "k8s-main-w-01",
    vmId: 1210,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
  k8sMainW2: {
    name: "k8s-main-w-02",
    vmId: 1220,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
  indigoControl1: {
    name: "srv-lx-k8s-indigo-control-01",
    vmId: 1300,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:00",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 64,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "control-plane"),
  },
  indigoControl2: {
    name: "srv-lx-k8s-indigo-control-02",
    vmId: 1310,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:10",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 64,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "control-plane"),
  },
  indigoControl3: {
    name: "srv-lx-k8s-indigo-control-03",
    vmId: 1320,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:20",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 64,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "control-plane"),
  },
  indigoWorker1: {
    name: "srv-lx-k8s-indigo-worker-01",
    vmId: 1330,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:30",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 128,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "worker"),
  },
  indigoWorker2: {
    name: "srv-lx-k8s-indigo-worker-02",
    vmId: 1340,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:40",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 128,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "worker"),
  },
  indigoWorker3: {
    name: "srv-lx-k8s-indigo-worker-03",
    vmId: 1350,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:13:50",
    vlanTag: 80,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 128,
    discard: true,
    tags: tags("kubernetes", "indigo-a", "worker"),
  },
} satisfies VmInventory

export const proxmox = {
  defaults,
  vms,
} as const
