import { tags, type VmDefaults, type VmInventory } from "@dsqr/model"

const defaults = {
  cpuCores: 2,
  memoryMiB: 4096,
  rootDiskSizeGiB: 32,
  tags: [],
} satisfies VmDefaults

const vms = {
  gateway: {
    name: "gateway",
    vmId: 1000,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 60,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    tags: tags("network"),
  },
  observability: {
    name: "beacon",
    resourceName: "observability",
    vmId: 1050,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 128,
    tags: tags("observability"),
  },
  khaos: {
    name: "khaos",
    vmId: 1100,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 8,
    memoryMiB: 8192,
    rootDiskSizeGiB: 200,
    discard: true,
    tags: tags("compute"),
  },
  knox: {
    name: "knox",
    vmId: 1120,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:20",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 16384,
    rootDiskSizeGiB: 200,
    tags: tags("compute"),
  },
  vault: {
    name: "vault",
    vmId: 1140,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-002",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:40",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 64,
    tags: tags("vault"),
  },
  backup: {
    name: "backup",
    vmId: 1160,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    macAddress: "02:00:00:00:11:60",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 2,
    memoryMiB: 4096,
    rootDiskSizeGiB: 128,
    tags: tags("backup"),
  },
  k8sMainCp1: {
    name: "k8s-main-cp-01",
    vmId: 1200,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 16384,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
  k8sMainW1: {
    name: "k8s-main-w-01",
    vmId: 1210,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
  k8sMainW2: {
    name: "k8s-main-w-02",
    vmId: 1220,
    nodeName: "pve",
    templateVmId: 9000,
    datastoreId: "ssd-dsqr-raid-001",
    bridge: "vmbr0",
    vlanTag: 30,
    cloudInitDiskDatastoreId: "local-lvm",
    cloudInitUserDataFileId: "local:snippets/user-data-test.yaml",
    cpuCores: 4,
    memoryMiB: 8192,
    rootDiskSizeGiB: 100,
    tags: tags("kubernetes"),
  },
} satisfies VmInventory

export const proxmox = {
  defaults,
  vms,
} as const
