apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gateway
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: cluster-networking
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-addon
spec:
  addresses:
    - 10.10.80.200/32
  autoAssign: false
  avoidBuggyIPs: true
