apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: cluster-networking
    platform.dsqr.dev/owner: platform
    platform.dsqr.dev/tier: platform-addon
spec:
  ipAddressPools:
    - ingress
  nodeSelectors:
    - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
