apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - platform-argocd.appproject.yaml
  - platform-argocd-access.appproject.yaml
  - platform-envoy-gateway.appproject.yaml
  - platform-gateway.appproject.yaml

labels:
  - pairs:
      platform.dsqr.dev/cluster: indigo
      platform.dsqr.dev/environment: production

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
      name: secrets
    patch: |-
      - op: replace
        path: /spec/description
        value: Trusted Indigo Vault-backed secret declarations
      - op: replace
        path: /spec/destinations
        value:
          - server: https://kubernetes.default.svc
            namespace: external-secrets
          - server: https://kubernetes.default.svc
            namespace: gateway-system
      - op: replace
        path: /spec/clusterResourceWhitelist
        value:
          - group: external-secrets.io
            kind: ClusterSecretStore
            name: vault-indigo
          - group: rbac.authorization.k8s.io
            kind: ClusterRoleBinding
            name: gateway-origin-issuer-auth-delegator
      - op: add
        path: /spec/namespaceResourceWhitelist/-
        value:
          group: ""
          kind: ServiceAccount
