apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: platform-external-secrets
    app.kubernetes.io/part-of: dsqr-gitops
    platform.dsqr.dev/tier: platform
spec:
  description: External Secrets Operator
  sourceRepos:
    - https://charts.external-secrets.io
    - https://github.com/0xdsqr/infrastructure.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: external-secrets
  clusterResourceWhitelist:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: externalsecret-validate
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: secretstore-validate
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: acraccesstokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beyondtrustworkloadcredentialsdynamicsecrets.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: cloudsmithaccesstokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterexternalsecrets.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustergenerators.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterpushsecrets.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustersecretstores.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: ecrauthorizationtokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: externalsecrets.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: fakes.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: gcraccesstokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: generatorstates.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: gitlabdeploytokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: githubaccesstokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: grafanas.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: mfas.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: passwords.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: pushsecrets.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: quayaccesstokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: secretstores.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: sshkeys.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: stssessiontokens.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: uuids.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: vaultdynamicsecrets.generators.external-secrets.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: webhooks.generators.external-secrets.io
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-secrets-cert-controller
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-secrets-controller
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-secrets-edit
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-secrets-servicebindings
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: external-secrets-view
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: external-secrets-auth-delegator
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: external-secrets-cert-controller
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: external-secrets-controller
  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
