import { FileSystem, Path } from "@effect/platform"
import { Console, Effect } from "effect"

import { GitOpsUsageError, GitOpsValidationError } from "./errors.ts"
import {
  asArray,
  asString,
  listDirectories,
  listFiles,
  mapFileSystemError,
  nestedValue,
  readText,
  readYamlRecord,
  renderKustomization,
  requirePathType,
  resolveDirectory,
  snapshotDirectory,
  validate,
  writeText,
  type YamlRecord,
} from "./runtime.ts"

export const gitOpsGenerateUsage = `Usage:
  gitops-generate [--check] [--repo-root PATH]

Render each cluster's declared Argo CD Applications from
gitops/templates/applications. Connection and repository settings come from
the cluster bootstrap Application. Every cluster is validated in a staging
tree before generated files are changed.

Options:
  --check      fail when committed output differs from a clean render
  --repo-root  repository root; defaults to the current directory`

const generatedMarkerPrefix = "Generated by `nix run .#gitops"
const applicationResourcePattern = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.yaml$/
const unresolvedVariablePattern = /\$\{[A-Z_][A-Z0-9_]*\}/

export type GitOpsGenerateOptions = {
  readonly check: boolean
  readonly repoRoot: string
}

export const parseGitOpsGenerateArguments = (
  argv: readonly string[],
  currentDirectory: string,
): Effect.Effect<GitOpsGenerateOptions | "help", GitOpsUsageError> => {
  let check = false
  let repoRoot = currentDirectory

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]
    if (argument === "-h" || argument === "--help") {
      return Effect.succeed("help")
    }
    if (argument === "--check") {
      check = true
      continue
    }
    if (argument === "--repo-root") {
      const value = argv[index + 1]
      if (value === undefined) {
        return Effect.fail(new GitOpsUsageError({ message: "--repo-root requires a path" }))
      }
      repoRoot = value
      index += 1
      continue
    }
    return Effect.fail(
      new GitOpsUsageError({
        message: `Unknown argument: ${argument}\n${gitOpsGenerateUsage}`,
      }),
    )
  }

  return Effect.succeed({ check, repoRoot })
}

const stringAt = (record: YamlRecord | undefined, ...path: readonly string[]) =>
  asString(nestedValue(record, ...path))

const generatedApplicationFiles = Effect.fn("GitOps.generate.generatedApplicationFiles")(function* (
  applicationsDirectory: string,
) {
  const path = yield* Path.Path
  const files = yield* listFiles(applicationsDirectory)
  const applicationFiles = files.filter(
    (file) => path.basename(file) !== "kustomization.yaml" && file.endsWith(".yaml"),
  )
  return yield* Effect.filter(
    applicationFiles,
    (file) => readText(file).pipe(Effect.map((source) => source.includes(generatedMarkerPrefix))),
    { concurrency: "unbounded" },
  )
})

const removeGeneratedApplications = Effect.fn("GitOps.generate.removeGeneratedApplications")(
  function* (applicationsDirectory: string) {
    const fileSystem = yield* FileSystem.FileSystem
    const files = yield* generatedApplicationFiles(applicationsDirectory)
    yield* Effect.forEach(
      files,
      (file) =>
        fileSystem
          .remove(file)
          .pipe(
            Effect.mapError(
              mapFileSystemError(file, `Unable to remove generated Application ${file}.`),
            ),
          ),
      { concurrency: 1, discard: true },
    )
  },
)

export const renderGitOpsApplicationTemplate = (
  source: string,
  values: Readonly<Record<string, string>>,
): Effect.Effect<string, GitOpsValidationError> => {
  const rendered = source.replace(
    /\$\{([A-Z_][A-Z0-9_]*)\}/g,
    (placeholder, name: string) => values[name] ?? placeholder,
  )
  return unresolvedVariablePattern.test(rendered)
    ? Effect.fail(
        new GitOpsValidationError({
          message: "Rendered Application contains an unresolved variable",
        }),
      )
    : Effect.succeed(rendered)
}

const validateRootApplication = Effect.fn("GitOps.generate.validateRootApplication")(function* (
  cluster: string,
  rootApplicationPath: string,
) {
  const root = yield* readYamlRecord(rootApplicationPath)
  const name = stringAt(root, "metadata", "name")
  const namespace = stringAt(root, "metadata", "namespace")
  const destinationNamespace = stringAt(root, "spec", "destination", "namespace")
  const destinationServer = stringAt(root, "spec", "destination", "server")
  const repositoryUrl = stringAt(root, "spec", "source", "repoURL")
  const targetRevision = stringAt(root, "spec", "source", "targetRevision")
  const sourcePath = stringAt(root, "spec", "source", "path")

  yield* validate(
    name === cluster,
    `Cluster directory ${cluster} disagrees with root Application name ${name ?? "<missing>"}`,
    rootApplicationPath,
  )
  yield* validate(
    namespace !== undefined && destinationNamespace === namespace,
    `Cluster ${cluster} root destination namespace must match its metadata namespace`,
    rootApplicationPath,
  )
  yield* validate(
    sourcePath === `gitops/clusters/${cluster}/applications`,
    `Cluster ${cluster} root Application must source gitops/clusters/${cluster}/applications`,
    rootApplicationPath,
  )
  yield* validate(
    destinationServer?.startsWith("https://") === true,
    `Cluster ${cluster} destination server must use HTTPS`,
    rootApplicationPath,
  )
  yield* validate(
    repositoryUrl?.startsWith("https://") === true,
    `Cluster ${cluster} repository URL must use HTTPS`,
    rootApplicationPath,
  )
  yield* validate(
    targetRevision !== undefined,
    `Cluster ${cluster} root Application must declare a target revision`,
    rootApplicationPath,
  )

  return {
    destinationServer: destinationServer!,
    namespace: namespace!,
    repositoryUrl: repositoryUrl!,
    targetRevision: targetRevision!,
  }
})

const validateRenderedApplication = Effect.fn("GitOps.generate.validateRenderedApplication")(
  function* (path: string, applicationName: string, namespace: string) {
    const application = yield* readYamlRecord(path)
    yield* validate(
      application.apiVersion === "argoproj.io/v1alpha1" &&
        application.kind === "Application" &&
        stringAt(application, "metadata", "name") === applicationName &&
        stringAt(application, "metadata", "namespace") === namespace,
      `Rendered Application ${applicationName} has invalid identity metadata`,
      path,
    )
  },
)

const renderCluster = Effect.fn("GitOps.generate.renderCluster")(function* (
  repoRoot: string,
  clusterDirectory: string,
) {
  const path = yield* Path.Path
  const cluster = path.basename(clusterDirectory)
  const applicationsDirectory = path.join(clusterDirectory, "applications")
  const applicationsKustomizationPath = path.join(applicationsDirectory, "kustomization.yaml")
  const bootstrapDirectory = path.join(clusterDirectory, "bootstrap")
  const rootApplicationPath = path.join(bootstrapDirectory, "argocd-app-of-apps.yaml")
  const templatesDirectory = path.join(repoRoot, "gitops", "templates", "applications")

  yield* requirePathType(
    applicationsKustomizationPath,
    "File",
    `Cluster ${cluster} is missing applications/kustomization.yaml`,
  )
  yield* requirePathType(
    rootApplicationPath,
    "File",
    `Cluster ${cluster} is missing bootstrap/argocd-app-of-apps.yaml`,
  )

  const root = yield* validateRootApplication(cluster, rootApplicationPath)
  const applicationsKustomization = yield* readYamlRecord(applicationsKustomizationPath)
  const resources = asArray(applicationsKustomization.resources) ?? []
  yield* validate(
    resources.length > 0,
    `Cluster ${cluster} must declare at least one Application`,
    applicationsKustomizationPath,
  )

  const applicationResources: string[] = []
  for (const resource of resources) {
    yield* validate(
      typeof resource === "string" && applicationResourcePattern.test(resource),
      `Cluster ${cluster} must contain only local Application YAML files: ${String(resource)}`,
      applicationsKustomizationPath,
    )
    applicationResources.push(resource as string)
  }

  const applicationNames = applicationResources.map((resource) =>
    resource.slice(0, -".yaml".length),
  )
  const duplicates = applicationNames
    .filter((name, index) => applicationNames.indexOf(name) !== index)
    .filter((name, index, names) => names.indexOf(name) === index)
    .sort()
  yield* validate(
    duplicates.length === 0,
    `Cluster ${cluster} declares duplicate Applications:\n${duplicates.join("\n")}`,
    applicationsKustomizationPath,
  )

  for (const applicationName of applicationNames) {
    const templatePath = path.join(templatesDirectory, `${applicationName}.yaml.tmpl`)
    yield* requirePathType(
      templatePath,
      "File",
      `Cluster ${cluster} is missing the ${applicationName} template`,
    )
  }

  yield* removeGeneratedApplications(applicationsDirectory)

  for (const applicationName of applicationNames) {
    const templatePath = path.join(templatesDirectory, `${applicationName}.yaml.tmpl`)
    const outputPath = path.join(applicationsDirectory, `${applicationName}.yaml`)
    const valuesCommonFile = `gitops/values/${applicationName}/common.yaml`
    const valuesOverlayFile = `gitops/values/${applicationName}/${cluster}.yaml`
    const valuesOverlayDirectory = `gitops/components/${applicationName}/overlays/${cluster}`
    const template = yield* readText(templatePath)
    const dependencies = [
      ["${VALUES_COMMON_FILE}", valuesCommonFile],
      ["${VALUES_OVERLAY_FILE}", valuesOverlayFile],
      ["${VALUES_OVERLAY_DIR}", `${valuesOverlayDirectory}/kustomization.yaml`],
    ] as const

    for (const [placeholder, dependency] of dependencies) {
      if (template.includes(placeholder)) {
        yield* requirePathType(
          path.join(repoRoot, dependency),
          "File",
          `Cluster ${cluster} Application ${applicationName} is missing ${dependency}`,
        )
      }
    }

    const rendered = yield* renderGitOpsApplicationTemplate(template, {
      APPLICATION_NAME: applicationName,
      ARGOCD_NAMESPACE: root.namespace,
      CLUSTER_NAME: cluster,
      DESTINATION_SERVER: root.destinationServer,
      VALUES_COMMON_FILE: valuesCommonFile,
      VALUES_OVERLAY_DIR: valuesOverlayDirectory,
      VALUES_OVERLAY_FILE: valuesOverlayFile,
      VALUES_REF: "$values",
      VALUES_REPO_URL: root.repositoryUrl,
      VALUES_TARGET_REVISION: root.targetRevision,
    }).pipe(
      Effect.mapError(
        () =>
          new GitOpsValidationError({
            message: `Rendered Application ${cluster}/${applicationName} contains an unresolved variable`,
            path: templatePath,
          }),
      ),
    )

    yield* writeText(outputPath, rendered)
    yield* validateRenderedApplication(outputPath, applicationName, root.namespace)
  }

  yield* renderKustomization(applicationsDirectory)
  yield* renderKustomization(bootstrapDirectory)
})

const renderGitOpsTree = Effect.fn("GitOps.generate.renderTree")(function* (repoRoot: string) {
  const path = yield* Path.Path
  const clustersDirectory = path.join(repoRoot, "gitops", "clusters")
  const templatesDirectory = path.join(repoRoot, "gitops", "templates", "applications")
  const expectedTreeMessage = `Expected gitops/clusters and gitops/templates/applications under ${repoRoot}`

  yield* requirePathType(clustersDirectory, "Directory", expectedTreeMessage)
  yield* requirePathType(templatesDirectory, "Directory", expectedTreeMessage)
  const clusterDirectories = yield* listDirectories(clustersDirectory)
  yield* validate(
    clusterDirectories.length > 0,
    `No GitOps clusters are declared under ${clustersDirectory}`,
    clustersDirectory,
  )
  yield* Effect.forEach(
    clusterDirectories,
    (clusterDirectory) => renderCluster(repoRoot, clusterDirectory),
    { concurrency: 1, discard: true },
  )
})

const describeDrift = (
  committed: readonly (readonly [string, string])[],
  rendered: readonly (readonly [string, string])[],
): readonly string[] => {
  const committedFiles = new Map(committed)
  const renderedFiles = new Map(rendered)
  return [...new Set([...committedFiles.keys(), ...renderedFiles.keys()])]
    .sort()
    .filter((file) => committedFiles.get(file) !== renderedFiles.get(file))
}

const commitGeneratedTree = Effect.fn("GitOps.generate.commit")(function* (
  committedGitOpsRoot: string,
  stagedGitOpsRoot: string,
) {
  const fileSystem = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const stagedClusters = yield* listDirectories(path.join(stagedGitOpsRoot, "clusters"))

  for (const stagedCluster of stagedClusters) {
    const cluster = path.basename(stagedCluster)
    const stagedApplications = path.join(stagedCluster, "applications")
    const committedApplications = path.join(
      committedGitOpsRoot,
      "clusters",
      cluster,
      "applications",
    )
    yield* removeGeneratedApplications(committedApplications)

    for (const stagedFile of yield* generatedApplicationFiles(stagedApplications)) {
      const destination = path.join(committedApplications, path.basename(stagedFile))
      const temporary = yield* fileSystem
        .makeTempFile({
          directory: committedApplications,
          prefix: `.${path.basename(stagedFile)}.`,
        })
        .pipe(
          Effect.mapError(
            mapFileSystemError(
              committedApplications,
              `Unable to create a temporary Application in ${committedApplications}.`,
            ),
          ),
        )
      yield* fileSystem
        .copyFile(stagedFile, temporary)
        .pipe(
          Effect.mapError(
            mapFileSystemError(stagedFile, `Unable to stage generated Application ${stagedFile}.`),
          ),
        )
      yield* fileSystem
        .rename(temporary, destination)
        .pipe(
          Effect.mapError(
            mapFileSystemError(
              destination,
              `Unable to atomically replace generated Application ${destination}.`,
            ),
          ),
        )
    }
  }
})

export const generateGitOps = Effect.fn("GitOps.generate")(function* (
  options: GitOpsGenerateOptions,
) {
  const fileSystem = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const repoRoot = yield* resolveDirectory(options.repoRoot)
  const committedGitOpsRoot = path.join(repoRoot, "gitops")
  const clustersDirectory = path.join(committedGitOpsRoot, "clusters")
  const templatesDirectory = path.join(committedGitOpsRoot, "templates", "applications")
  const expectedTreeMessage = `Expected gitops/clusters and gitops/templates/applications under ${repoRoot}`
  yield* requirePathType(clustersDirectory, "Directory", expectedTreeMessage)
  yield* requirePathType(templatesDirectory, "Directory", expectedTreeMessage)

  yield* Effect.scoped(
    Effect.gen(function* () {
      const workspace = yield* fileSystem
        .makeTempDirectoryScoped({ prefix: "gitops-generate-" })
        .pipe(
          Effect.mapError(
            mapFileSystemError(repoRoot, "Unable to create the GitOps generation staging tree."),
          ),
        )
      const stagedGitOpsRoot = path.join(workspace, "gitops")
      yield* fileSystem
        .copy(committedGitOpsRoot, stagedGitOpsRoot)
        .pipe(
          Effect.mapError(
            mapFileSystemError(
              committedGitOpsRoot,
              "Unable to copy GitOps sources into the staging tree.",
            ),
          ),
        )
      yield* renderGitOpsTree(workspace)

      if (options.check) {
        const [committed, rendered] = yield* Effect.all([
          snapshotDirectory(clustersDirectory),
          snapshotDirectory(path.join(stagedGitOpsRoot, "clusters")),
        ])
        const drift = describeDrift(committed, rendered)
        yield* validate(
          drift.length === 0,
          `Generated GitOps output differs from the committed tree:\n${drift.join("\n")}`,
          clustersDirectory,
        )
        return
      }

      yield* commitGeneratedTree(committedGitOpsRoot, stagedGitOpsRoot)
    }),
  )
})

export const runGitOpsGenerateCli = Effect.fn("GitOps.generateCli")(function* (
  argv: readonly string[],
) {
  const repoRoot = yield* resolveDirectory(".")
  const options = yield* parseGitOpsGenerateArguments(argv, repoRoot)
  if (options === "help") {
    yield* Console.log(gitOpsGenerateUsage)
    return
  }
  yield* generateGitOps(options)
})
