apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-foundation.yaml
  - argocd-config.yaml
  - cilium.yaml
  - metallb.yaml
  - metallb-config.yaml
  - traefik.yaml
  - metrics-server.yaml
  - kube-state-metrics.yaml
  - k8s-monitoring.yaml
  - external-secrets.yaml
  - external-secrets-config.yaml
  - dotdev-web.yaml
  - dotdev-studio.yaml
  - dotdev-labs.yaml
  - fidara.yaml
  - twt-web.yaml
  - twt-admin.yaml

labels:
  - pairs:
      homelab.dev/cluster: hub-a
      homelab.dev/environment: homelab
