apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: dsqr-hubble-server-tls
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  path: pki_indigo_hubble/issue/indigo-hubble-server
  method: POST
  resultType: Data
  parameters:
    common_name: "*.indigo.hubble-grpc.cilium.io"
    ttl: 720h
  provider:
    server: https://vault.service.home.arpa:8200
    caProvider:
      type: ConfigMap
      name: dsqr-home-root-ca
      key: ca.crt
    auth:
      kubernetes:
        mountPath: kubernetes-indigo
        role: indigo-hubble-server-issuer
        serviceAccountRef:
          name: hubble-server-issuer
